"""feat: optimize query

Revision ID: 14f006ab5858
Revises: 2a0685b4f2ba
Create Date: 2025-02-24 11:32:33.712295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14f006ab5858"
down_revision: Union[str, None] = "2a0685b4f2ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buildings",
        sa.Column(
            "amenity_category", sa.String(), server_default="Residential", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buildings", "amenity_category")
    # ### end Alembic commands ###
