"""feat: add buildings height

Revision ID: 2a0685b4f2ba
Revises: 248ff61ccde2
Create Date: 2025-02-19 15:26:47.527050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a0685b4f2ba"
down_revision: Union[str, None] = "248ff61ccde2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buildings", sa.Column("height", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buildings", "height")
    # ### end Alembic commands ###
