"""feat: fix default category

Revision ID: c0b327f37e81
Revises: 14f006ab5858
Create Date: 2025-02-24 12:08:46.889319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0b327f37e81"
down_revision: Union[str, None] = "14f006ab5858"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "buildings",
        "amenity_category",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'Residential'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "buildings",
        "amenity_category",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'Residential'::character varying"),
    )
    # ### end Alembic commands ###
